// <auto-generated />
using System;
using FashionStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FashionStore.Migrations
{
    [DbContext(typeof(FashionStoreContext))]
    [Migration("20251116091530_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FashionStore.Models.ChiTietDonHang", b =>
                {
                    b.Property<string>("Ma_DonHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_SanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.HasKey("Ma_DonHang", "Ma_SanPham");

                    b.HasIndex("Ma_SanPham");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("FashionStore.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("Ma_GioHang")
                        .HasColumnType("int");

                    b.Property<string>("Ma_SanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.HasKey("Ma_GioHang", "Ma_SanPham");

                    b.HasIndex("Ma_SanPham");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("FashionStore.Models.DanhMuc", b =>
                {
                    b.Property<string>("Ma_DanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_DanhMucCha")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_DanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Ma_DanhMuc");

                    b.HasIndex("Ma_DanhMucCha");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("FashionStore.Models.DonHang", b =>
                {
                    b.Property<string>("Ma_DonHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("KhachHangMa_KhachHang")
                        .HasColumnType("int");

                    b.Property<int>("Ma_KhachHang")
                        .HasColumnType("int");

                    b.Property<int>("Ma_PhuongThuc")
                        .HasColumnType("int");

                    b.Property<string>("Ma_Voucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay_Dat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhuongThucThanhToanMa_PhuongThuc")
                        .HasColumnType("int");

                    b.Property<decimal>("Tong_Tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Trang_Thai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherMa_Voucher")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Ma_DonHang");

                    b.HasIndex("KhachHangMa_KhachHang");

                    b.HasIndex("PhuongThucThanhToanMa_PhuongThuc");

                    b.HasIndex("VoucherMa_Voucher");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("FashionStore.Models.GioHang", b =>
                {
                    b.Property<int>("Ma_GioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma_GioHang"));

                    b.Property<int?>("KhachHangMa_KhachHang")
                        .HasColumnType("int");

                    b.Property<int>("Ma_KhachHang")
                        .HasColumnType("int");

                    b.HasKey("Ma_GioHang");

                    b.HasIndex("KhachHangMa_KhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("FashionStore.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanPhamMa_SanPham")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("SanPhamMa_SanPham");

                    b.ToTable("HinhAnhSanPhams");
                });

            modelBuilder.Entity("FashionStore.Models.KhachHang", b =>
                {
                    b.Property<int>("Ma_KhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma_KhachHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hinh_Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ma_TaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_KhachHang");

                    b.HasIndex("Ma_TaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("FashionStore.Models.NhanVien", b =>
                {
                    b.Property<int>("Ma_NhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma_NhanVien"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hinh_Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ma_TaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_NhanVien");

                    b.HasIndex("Ma_TaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("FashionStore.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("Ma_PhuongThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma_PhuongThuc"));

                    b.Property<string>("Ten_PhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_PhuongThuc");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("FashionStore.Models.SanPham", b =>
                {
                    b.Property<string>("Ma_SanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DanhMucMa_DanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Gia_Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kich_Thuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_DanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mau_Sac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mo_Ta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.Property<string>("Ten_SanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Ma_SanPham");

                    b.HasIndex("DanhMucMa_DanhMuc");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("FashionStore.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Ma_TaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma_TaiKhoan"));

                    b.Property<bool>("Da_XacThuc")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Han_XacThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ma_VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ma_XacThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mat_Khau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten_DangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Ma_TaiKhoan");

                    b.HasIndex("Ma_VaiTro");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("FashionStore.Models.VaiTro", b =>
                {
                    b.Property<string>("Ma_VaiTro")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_VaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("FashionStore.Models.Voucher", b =>
                {
                    b.Property<string>("Ma_Voucher")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("GiaTri_ToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Giam_PhanTram")
                        .HasColumnType("int");

                    b.Property<decimal?>("Giam_Tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Ngay_BatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngay_KetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("So_LanDung")
                        .HasColumnType("int");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Ma_Voucher");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("FashionStore.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("FashionStore.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Ma_DonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionStore.Models.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Ma_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FashionStore.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("FashionStore.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("Ma_GioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionStore.Models.SanPham", "SanPham")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("Ma_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FashionStore.Models.DanhMuc", b =>
                {
                    b.HasOne("FashionStore.Models.DanhMuc", "DanhMucCha")
                        .WithMany("DanhMucCon")
                        .HasForeignKey("Ma_DanhMucCha")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("FashionStore.Models.DonHang", b =>
                {
                    b.HasOne("FashionStore.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMa_KhachHang");

                    b.HasOne("FashionStore.Models.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("DonHangs")
                        .HasForeignKey("PhuongThucThanhToanMa_PhuongThuc");

                    b.HasOne("FashionStore.Models.Voucher", "Voucher")
                        .WithMany("DonHangs")
                        .HasForeignKey("VoucherMa_Voucher");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("FashionStore.Models.GioHang", b =>
                {
                    b.HasOne("FashionStore.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangMa_KhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("FashionStore.Models.HinhAnhSanPham", b =>
                {
                    b.HasOne("FashionStore.Models.SanPham", "SanPham")
                        .WithMany("HinhAnhSanPhams")
                        .HasForeignKey("SanPhamMa_SanPham");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FashionStore.Models.KhachHang", b =>
                {
                    b.HasOne("FashionStore.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("FashionStore.Models.KhachHang", "Ma_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("FashionStore.Models.NhanVien", b =>
                {
                    b.HasOne("FashionStore.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("FashionStore.Models.NhanVien", "Ma_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("FashionStore.Models.SanPham", b =>
                {
                    b.HasOne("FashionStore.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucMa_DanhMuc");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("FashionStore.Models.TaiKhoan", b =>
                {
                    b.HasOne("FashionStore.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("Ma_VaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("FashionStore.Models.DanhMuc", b =>
                {
                    b.Navigation("DanhMucCon");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("FashionStore.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("FashionStore.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("FashionStore.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("FashionStore.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("HinhAnhSanPhams");
                });

            modelBuilder.Entity("FashionStore.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FashionStore.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("FashionStore.Models.Voucher", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
